# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Breeder's Choice Packaged Woodshavings - Premium Animal Bedding"
email: "jarrod@breederschoice.com.au"
description: >- # this means to ignore newlines until "baseurl:"
  Premium quality pine woodshavings for poultry, equine, and small animal bedding. Kiln-dried, dust-extracted, and screened for optimal animal health and comfort. Available in 14kg bales.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://breederschoice.com.au" # the base hostname & protocol for your site, e.g. http://example.com
author: "Breeder's Choice"
phone: "(03) 5232 2200"
phone_international: "+613 5232 2200"
fax: "+613 5232 2270"
address_postal: "Jarrod Hay, PO Box 530, Colac, VIC 3250 Australia"
address_physical: "92-98 Forest St, Colac, VIC 3250"

# SEO related
keywords: "woodshavings, animal bedding, horse bedding, poultry bedding, pine shavings, kiln dried shavings, dust extracted shavings, chicken bedding, stable bedding, animal litter, pet bedding, livestock bedding, horse stable bedding, chicken coop bedding, small animal bedding"
logo: "/images/logo2.png"
twitter_card: "summary_large_image"

stockistscsv: https://dl.dropbox.com/s/b3gmuxhrrye00gl/breeders_choice.csv

# Build settings
markdown: kramdown

repository: zackdesign/breederschoice.github.io

plugins:
  - jekyll-email-protect
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
